# Generated by Django 4.2.25 on 2025-10-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=150, verbose_name='Nome do Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filial', models.CharField(max_length=150, unique=True, verbose_name='Nome da Filial')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=150, verbose_name='Nome do Setor')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255, verbose_name='Nome do Usuário')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('grupo', models.CharField(blank=True, max_length=5, null=True)),
                ('perfil_cargo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Perfil do Cargo')),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(default='Em estoque', max_length=50)),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, null=True)),
                ('processador', models.CharField(blank=True, max_length=150, null=True)),
                ('ram_gb', models.IntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('armazenamento_gb', models.IntegerField(blank=True, null=True, verbose_name='Armazenamento (GB)')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.setor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.filial'),
        ),
    ]
