# Generated by Django 4.2.25 on 2025-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='maquina',
            name='tag_patrimonio',
            field=models.CharField(default='TEMP-00000', editable=False, max_length=10, unique=True, verbose_name='ID Interno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('DT', 'Desktop'), ('NB', 'Notebook'), ('MP', 'Mini PC')], default='NB', max_length=2, verbose_name='Tipo de Máquina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cod_interno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operacional'),
        ),
    ]
