# Generated by Django 4.2.25 on 2025-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_filial_options_alter_setor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='tag_patrimonio',
            new_name='id_maquina',
        ),
        migrations.AddField(
            model_name='maquina',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='dominio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domínio'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='frequencia_memoria_mhz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequência da Memória (MHz)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='geracao_memoria',
            field=models.CharField(blank=True, choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=4, null=True, verbose_name='Geração da Memória'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='mac_address_lan',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='MAC Address LAN'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='mac_address_wifi',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='MAC Address Wi-Fi'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='placa_mae',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa Mãe'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo_armazenamento',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], max_length=4, null=True, verbose_name='Tipo de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='status',
            field=models.CharField(choices=[('Em uso', 'Em uso'), ('Disponível', 'Disponível'), ('Em manutenção', 'Em manutenção')], default='Disponível', max_length=50),
        ),
    ]
